import type { FAClientRecord, FAHolding, AcctClientRecord } from "./types";

export const FA_DEMO_CLIENTS: FAClientRecord[] = [
  {
    // Roth conversion candidate #1: high bracket now, expecting lower in retirement
    client_id: "C-1001",
    age: 58,
    filing_status: "MFJ",
    federal_tax_bracket: 0.32,
    state_tax_rate: 0.05,
    risk_tolerance: "Moderate",
    investment_objective: "Retirement Income",
    time_horizon: "5-10 years",
    annual_income: 285000,
    liquid_net_worth: 1800000,
    total_net_worth: 3200000,
    liquidity_needs: "Low",
    retirement_age_target: 63,
    has_pension: true,
    social_security_start_age: 67,
    notes: "Planning to retire in 5 years. Pension will cover ~40% of expenses. Interested in reducing future RMD burden.",
  },
  {
    // Roth conversion candidate #2: large Traditional IRA, high bracket
    client_id: "C-1002",
    age: 52,
    filing_status: "Single",
    federal_tax_bracket: 0.35,
    state_tax_rate: 0.0,
    risk_tolerance: "Moderate Aggressive",
    investment_objective: "Growth & Income",
    time_horizon: "10-15 years",
    annual_income: 420000,
    liquid_net_worth: 2400000,
    total_net_worth: 3800000,
    liquidity_needs: "Low",
    retirement_age_target: 60,
    notes: "Lives in TX (no state tax). $1.2M in Traditional IRA. Wants to minimize RMDs. Considering early retirement.",
  },
  {
    // Dangerous tech concentration
    client_id: "C-1003",
    age: 44,
    filing_status: "MFJ",
    federal_tax_bracket: 0.37,
    state_tax_rate: 0.093,
    risk_tolerance: "Aggressive",
    investment_objective: "Capital Appreciation",
    time_horizon: "15+ years",
    annual_income: 650000,
    liquid_net_worth: 3100000,
    total_net_worth: 5200000,
    liquidity_needs: "Low",
    num_dependents: 2,
    notes: "Tech executive. Most wealth from RSUs. Reluctant to sell NVDA — emotional attachment to gains.",
  },
  {
    // Tax-loss harvesting opportunity
    client_id: "C-1004",
    age: 39,
    filing_status: "MFJ",
    federal_tax_bracket: 0.32,
    state_tax_rate: 0.06,
    risk_tolerance: "Moderate Aggressive",
    investment_objective: "Growth",
    time_horizon: "15+ years",
    annual_income: 310000,
    liquid_net_worth: 950000,
    total_net_worth: 1600000,
    liquidity_needs: "Moderate",
    num_dependents: 3,
    annual_expenses: 180000,
    notes: "Invested heavily in growth stocks and crypto-adjacent names near late 2021 highs.",
  },
  {
    // Risk mismatch: Conservative stated, aggressive portfolio
    client_id: "C-1005",
    age: 67,
    filing_status: "MFJ",
    federal_tax_bracket: 0.24,
    state_tax_rate: 0.04,
    risk_tolerance: "Conservative",
    investment_objective: "Capital Preservation",
    time_horizon: "5-10 years",
    annual_income: 120000,
    liquid_net_worth: 890000,
    total_net_worth: 1400000,
    liquidity_needs: "High",
    has_pension: false,
    social_security_start_age: 70,
    notes: "Recently retired. Needs portfolio income to bridge until Social Security starts. Expressed concern about market volatility.",
  },
  {
    // Near retirement, too much equity
    client_id: "C-1006",
    age: 62,
    filing_status: "Single",
    federal_tax_bracket: 0.32,
    state_tax_rate: 0.07,
    risk_tolerance: "Moderate",
    investment_objective: "Retirement Income",
    time_horizon: "3-5 years",
    annual_income: 195000,
    liquid_net_worth: 1100000,
    total_net_worth: 1700000,
    liquidity_needs: "Moderate",
    retirement_age_target: 65,
    annual_expenses: 95000,
    notes: "Wants to retire at 65. No pension. Will rely on portfolio + SS. Concerned about sequence-of-return risk.",
  },
  {
    // Poor asset location
    client_id: "C-1007",
    age: 48,
    filing_status: "MFJ",
    federal_tax_bracket: 0.35,
    state_tax_rate: 0.05,
    risk_tolerance: "Moderate",
    investment_objective: "Balanced Growth",
    time_horizon: "10-15 years",
    annual_income: 380000,
    liquid_net_worth: 1650000,
    total_net_worth: 2900000,
    liquidity_needs: "Low",
    num_dependents: 2,
    notes: "Has both taxable and tax-deferred accounts but holdings are not optimally located for tax efficiency.",
  },
  {
    // Well-optimized benchmark client
    client_id: "C-1008",
    age: 55,
    filing_status: "MFJ",
    federal_tax_bracket: 0.24,
    state_tax_rate: 0.05,
    risk_tolerance: "Moderate",
    investment_objective: "Retirement Income",
    time_horizon: "10-15 years",
    annual_income: 210000,
    liquid_net_worth: 1400000,
    total_net_worth: 2100000,
    liquidity_needs: "Low",
    retirement_age_target: 67,
    has_pension: true,
    social_security_start_age: 67,
    notes: "Well-diversified. Good asset location. On track for retirement goals.",
  },
];

export const FA_DEMO_HOLDINGS: FAHolding[] = [
  // C-1001 — Roth candidate: large Traditional IRA
  { client_id: "C-1001", ticker: "VTI", shares: 800, cost_basis: 120, current_price: 268, account_type: "Traditional IRA", date_purchased: "2016-03-15" },
  { client_id: "C-1001", ticker: "VXUS", shares: 400, cost_basis: 45, current_price: 58, account_type: "Traditional IRA", date_purchased: "2017-06-10" },
  { client_id: "C-1001", ticker: "BND", shares: 600, cost_basis: 78, current_price: 72, account_type: "Traditional IRA", date_purchased: "2018-01-20" },
  { client_id: "C-1001", ticker: "VTI", shares: 200, cost_basis: 180, current_price: 268, account_type: "Taxable", date_purchased: "2020-04-01" },
  { client_id: "C-1001", ticker: "AAPL", shares: 150, cost_basis: 95, current_price: 192, account_type: "Taxable", date_purchased: "2019-08-12" },
  { client_id: "C-1001", ticker: "BND", shares: 300, cost_basis: 80, current_price: 72, account_type: "Roth IRA", date_purchased: "2019-02-14" },

  // C-1002 — Roth candidate: massive Traditional IRA
  { client_id: "C-1002", ticker: "VOO", shares: 1200, cost_basis: 280, current_price: 512, account_type: "Traditional IRA", date_purchased: "2015-05-20" },
  { client_id: "C-1002", ticker: "QQQ", shares: 500, cost_basis: 180, current_price: 478, account_type: "Traditional IRA", date_purchased: "2016-11-01" },
  { client_id: "C-1002", ticker: "VTI", shares: 300, cost_basis: 200, current_price: 268, account_type: "Roth IRA", date_purchased: "2018-07-15" },
  { client_id: "C-1002", ticker: "MSFT", shares: 200, cost_basis: 110, current_price: 415, account_type: "Taxable", date_purchased: "2017-03-22" },
  { client_id: "C-1002", ticker: "SCHD", shares: 400, cost_basis: 55, current_price: 82, account_type: "Taxable", date_purchased: "2019-09-05", annual_dividend_yield: 0.035 },

  // C-1003 — Dangerous tech concentration (>40% NVDA+AAPL+MSFT)
  { client_id: "C-1003", ticker: "NVDA", shares: 1500, cost_basis: 15, current_price: 138, account_type: "Taxable", date_purchased: "2019-01-10" },
  { client_id: "C-1003", ticker: "AAPL", shares: 600, cost_basis: 45, current_price: 192, account_type: "Taxable", date_purchased: "2018-06-01" },
  { client_id: "C-1003", ticker: "MSFT", shares: 400, cost_basis: 85, current_price: 415, account_type: "Taxable", date_purchased: "2017-09-15" },
  { client_id: "C-1003", ticker: "VOO", shares: 200, cost_basis: 350, current_price: 512, account_type: "401k", date_purchased: "2021-01-05" },
  { client_id: "C-1003", ticker: "AMZN", shares: 100, cost_basis: 95, current_price: 198, account_type: "Taxable", date_purchased: "2020-03-20" },
  { client_id: "C-1003", ticker: "BND", shares: 200, cost_basis: 76, current_price: 72, account_type: "401k", date_purchased: "2021-06-01" },

  // C-1004 — Tax-loss harvesting (bought near 2021 highs)
  { client_id: "C-1004", ticker: "ARKK", shares: 500, cost_basis: 148, current_price: 52, account_type: "Taxable", date_purchased: "2021-11-08" },
  { client_id: "C-1004", ticker: "COIN", shares: 200, cost_basis: 320, current_price: 225, account_type: "Taxable", date_purchased: "2021-10-15" },
  { client_id: "C-1004", ticker: "SQ", shares: 300, cost_basis: 240, current_price: 78, account_type: "Taxable", date_purchased: "2021-08-20" },
  { client_id: "C-1004", ticker: "PYPL", shares: 400, cost_basis: 270, current_price: 68, account_type: "Taxable", date_purchased: "2021-09-01" },
  { client_id: "C-1004", ticker: "VTI", shares: 250, cost_basis: 210, current_price: 268, account_type: "401k", date_purchased: "2020-06-15" },
  { client_id: "C-1004", ticker: "VXUS", shares: 150, cost_basis: 52, current_price: 58, account_type: "401k", date_purchased: "2020-06-15" },

  // C-1005 — Risk mismatch: says Conservative but holds aggressive positions
  { client_id: "C-1005", ticker: "TQQQ", shares: 300, cost_basis: 35, current_price: 72, account_type: "Taxable", date_purchased: "2023-01-10" },
  { client_id: "C-1005", ticker: "NVDA", shares: 200, cost_basis: 25, current_price: 138, account_type: "Taxable", date_purchased: "2020-05-20" },
  { client_id: "C-1005", ticker: "TSLA", shares: 150, cost_basis: 180, current_price: 248, account_type: "Taxable", date_purchased: "2022-06-01" },
  { client_id: "C-1005", ticker: "VOO", shares: 400, cost_basis: 300, current_price: 512, account_type: "Traditional IRA", date_purchased: "2019-04-10" },
  { client_id: "C-1005", ticker: "BND", shares: 100, cost_basis: 78, current_price: 72, account_type: "Traditional IRA", date_purchased: "2020-01-15" },

  // C-1006 — Near retirement, too much equity (90%+ equities)
  { client_id: "C-1006", ticker: "VOO", shares: 600, cost_basis: 250, current_price: 512, account_type: "Traditional IRA", date_purchased: "2017-05-01" },
  { client_id: "C-1006", ticker: "VTI", shares: 400, cost_basis: 170, current_price: 268, account_type: "401k", date_purchased: "2018-03-20" },
  { client_id: "C-1006", ticker: "AAPL", shares: 200, cost_basis: 65, current_price: 192, account_type: "Taxable", date_purchased: "2016-09-10" },
  { client_id: "C-1006", ticker: "MSFT", shares: 100, cost_basis: 75, current_price: 415, account_type: "Taxable", date_purchased: "2016-09-10" },
  { client_id: "C-1006", ticker: "AGG", shares: 50, cost_basis: 105, current_price: 98, account_type: "Traditional IRA", date_purchased: "2021-01-15" },

  // C-1007 — Poor asset location: dividends in taxable, growth in IRA
  { client_id: "C-1007", ticker: "VYM", shares: 500, cost_basis: 85, current_price: 118, account_type: "Taxable", date_purchased: "2019-02-01", annual_dividend_yield: 0.032 },
  { client_id: "C-1007", ticker: "SCHD", shares: 600, cost_basis: 52, current_price: 82, account_type: "Taxable", date_purchased: "2018-07-15", annual_dividend_yield: 0.035 },
  { client_id: "C-1007", ticker: "O", shares: 300, cost_basis: 55, current_price: 58, account_type: "Taxable", date_purchased: "2019-11-20", annual_dividend_yield: 0.056 },
  { client_id: "C-1007", ticker: "QQQ", shares: 200, cost_basis: 220, current_price: 478, account_type: "Traditional IRA", date_purchased: "2020-03-25" },
  { client_id: "C-1007", ticker: "AMZN", shares: 100, cost_basis: 105, current_price: 198, account_type: "Traditional IRA", date_purchased: "2020-03-25" },
  { client_id: "C-1007", ticker: "GOOGL", shares: 150, cost_basis: 90, current_price: 175, account_type: "Roth IRA", date_purchased: "2020-06-10" },

  // C-1008 — Well-optimized benchmark
  { client_id: "C-1008", ticker: "VTI", shares: 400, cost_basis: 180, current_price: 268, account_type: "Taxable", date_purchased: "2018-04-10" },
  { client_id: "C-1008", ticker: "VXUS", shares: 200, cost_basis: 48, current_price: 58, account_type: "Taxable", date_purchased: "2018-04-10" },
  { client_id: "C-1008", ticker: "BND", shares: 500, cost_basis: 80, current_price: 72, account_type: "Traditional IRA", date_purchased: "2019-01-02" },
  { client_id: "C-1008", ticker: "VTIP", shares: 300, cost_basis: 50, current_price: 48, account_type: "Traditional IRA", date_purchased: "2019-01-02" },
  { client_id: "C-1008", ticker: "VTI", shares: 300, cost_basis: 200, current_price: 268, account_type: "Roth IRA", date_purchased: "2020-01-15" },
  { client_id: "C-1008", ticker: "VGT", shares: 100, cost_basis: 280, current_price: 530, account_type: "Roth IRA", date_purchased: "2020-01-15" },
];

export const ACCT_DEMO_CLIENTS: AcctClientRecord[] = [
  {
    // AMT risk #1: high W-2, ISO exercises
    client_id: "C-2001",
    filing_status: "MFJ",
    num_dependents: 2,
    state_of_residence: "CA",
    w2_income: 425000,
    self_employment_income: 0,
    business_income_loss: 0,
    rental_income_loss: 0,
    capital_gains_short: 15000,
    capital_gains_long: 45000,
    interest_income: 8200,
    dividend_income_qualified: 12000,
    dividend_income_ordinary: 3500,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 0,
    mortgage_interest: 28000,
    salt_paid: 52000,
    charitable_cash: 15000,
    charitable_noncash: 5000,
    medical_expenses: 2000,
    student_loan_interest: 0,
    business_expenses: 0,
    estimated_tax_payments: 40000,
    withholding: 95000,
    prior_year_overpayment: 0,
    amt_preference_items: 18000,
    iso_exercise_spread: 120000,
    notes: "Exercised 2,000 ISOs this year. Concerned about AMT impact.",
  },
  {
    // AMT risk #2: high income, large SALT
    client_id: "C-2002",
    filing_status: "MFJ",
    num_dependents: 3,
    state_of_residence: "NY",
    w2_income: 380000,
    self_employment_income: 0,
    business_income_loss: 0,
    rental_income_loss: -12000,
    capital_gains_short: 0,
    capital_gains_long: 85000,
    interest_income: 6500,
    dividend_income_qualified: 18000,
    dividend_income_ordinary: 4200,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 0,
    mortgage_interest: 35000,
    salt_paid: 68000,
    charitable_cash: 20000,
    charitable_noncash: 0,
    medical_expenses: 3500,
    student_loan_interest: 0,
    business_expenses: 0,
    estimated_tax_payments: 55000,
    withholding: 82000,
    prior_year_overpayment: 5000,
    amt_preference_items: 25000,
    notes: "NYC resident. Very high SALT. Lost $58k to SALT cap last year.",
  },
  {
    // 199A QBI opportunity
    client_id: "C-2003",
    filing_status: "MFJ",
    num_dependents: 1,
    state_of_residence: "TX",
    w2_income: 0,
    self_employment_income: 95000,
    business_income_loss: 185000,
    rental_income_loss: 22000,
    capital_gains_short: 0,
    capital_gains_long: 12000,
    interest_income: 3200,
    dividend_income_qualified: 4500,
    dividend_income_ordinary: 1200,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 0,
    mortgage_interest: 14000,
    salt_paid: 6000,
    charitable_cash: 8000,
    charitable_noncash: 2000,
    medical_expenses: 1500,
    student_loan_interest: 0,
    business_expenses: 35000,
    estimated_tax_payments: 45000,
    withholding: 0,
    prior_year_overpayment: 3000,
    notes: "Owns consulting firm (S-corp). Pass-through income should qualify for 199A. No state income tax.",
  },
  {
    // Charitable bunching candidate
    client_id: "C-2004",
    filing_status: "MFJ",
    num_dependents: 0,
    state_of_residence: "FL",
    w2_income: 175000,
    self_employment_income: 0,
    business_income_loss: 0,
    rental_income_loss: 0,
    capital_gains_short: 5000,
    capital_gains_long: 8000,
    interest_income: 4500,
    dividend_income_qualified: 6000,
    dividend_income_ordinary: 2000,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 0,
    mortgage_interest: 12000,
    salt_paid: 4000,
    charitable_cash: 10000,
    charitable_noncash: 3000,
    medical_expenses: 800,
    student_loan_interest: 0,
    business_expenses: 0,
    estimated_tax_payments: 10000,
    withholding: 38000,
    prior_year_overpayment: 0,
    notes: "Typically gives $10-13k/yr to charity. Itemized deductions are close to standard deduction threshold.",
  },
  {
    // Underpayment risk
    client_id: "C-2005",
    filing_status: "Single",
    num_dependents: 0,
    state_of_residence: "WA",
    w2_income: 165000,
    self_employment_income: 0,
    business_income_loss: 0,
    rental_income_loss: 0,
    capital_gains_short: 95000,
    capital_gains_long: 140000,
    interest_income: 12000,
    dividend_income_qualified: 8000,
    dividend_income_ordinary: 5000,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 0,
    mortgage_interest: 0,
    salt_paid: 0,
    charitable_cash: 5000,
    charitable_noncash: 0,
    medical_expenses: 0,
    student_loan_interest: 0,
    business_expenses: 0,
    estimated_tax_payments: 8000,
    withholding: 35000,
    prior_year_overpayment: 0,
    notes: "Had an unusually large year of stock sales. No state income tax (WA). Estimated payments seem low relative to gains.",
  },
  {
    // Multi-state complexity
    client_id: "C-2006",
    filing_status: "MFJ",
    num_dependents: 2,
    state_of_residence: "NJ",
    w2_income: 220000,
    self_employment_income: 45000,
    business_income_loss: 0,
    rental_income_loss: 18000,
    capital_gains_short: 8000,
    capital_gains_long: 25000,
    interest_income: 5500,
    dividend_income_qualified: 7000,
    dividend_income_ordinary: 2500,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 12000,
    mortgage_interest: 22000,
    salt_paid: 38000,
    charitable_cash: 12000,
    charitable_noncash: 0,
    medical_expenses: 6000,
    student_loan_interest: 2500,
    business_expenses: 15000,
    estimated_tax_payments: 30000,
    withholding: 48000,
    prior_year_overpayment: 2000,
    notes: "Primary residence in NJ, rental property in PA, consulting work sourced in NY. Needs multi-state filing. Moved from NY to NJ mid-year last year.",
  },
  {
    // DAF candidate: high-income year
    client_id: "C-2007",
    filing_status: "Single",
    num_dependents: 0,
    state_of_residence: "MA",
    w2_income: 520000,
    self_employment_income: 0,
    business_income_loss: 0,
    rental_income_loss: 0,
    capital_gains_short: 0,
    capital_gains_long: 200000,
    interest_income: 15000,
    dividend_income_qualified: 22000,
    dividend_income_ordinary: 8000,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 75000,
    mortgage_interest: 18000,
    salt_paid: 45000,
    charitable_cash: 25000,
    charitable_noncash: 10000,
    medical_expenses: 1000,
    student_loan_interest: 0,
    business_expenses: 0,
    estimated_tax_payments: 80000,
    withholding: 130000,
    prior_year_overpayment: 0,
    notes: "Received large bonus + stock vesting this year. Historically charitable ($25-35k/yr). Would consider DAF to front-load deductions in this high-income year.",
  },
  {
    // Straightforward baseline
    client_id: "C-2008",
    filing_status: "MFJ",
    num_dependents: 2,
    state_of_residence: "OH",
    w2_income: 135000,
    self_employment_income: 0,
    business_income_loss: 0,
    rental_income_loss: 0,
    capital_gains_short: 0,
    capital_gains_long: 5000,
    interest_income: 2500,
    dividend_income_qualified: 3000,
    dividend_income_ordinary: 1000,
    social_security_income: 0,
    pension_income: 0,
    ira_distributions: 0,
    other_income: 0,
    mortgage_interest: 9000,
    salt_paid: 8500,
    charitable_cash: 6000,
    charitable_noncash: 0,
    medical_expenses: 1500,
    student_loan_interest: 1800,
    business_expenses: 0,
    estimated_tax_payments: 0,
    withholding: 28000,
    prior_year_overpayment: 1200,
    notes: "Straightforward dual-income household. Standard W-2 employment. Itemized deductions are close to standard deduction — worth evaluating.",
  },
];
