import type { ReportSection } from "./report-engine";
import type { ClientNameMap } from "./report-engine";

export interface ReportMeta {
  firmName: string;
  date: string;
  disclaimer: string;
  clientSummaries: {
    clientId: string;
    name: string;
    meta: string;
  }[];
}

function buildReportHTML(
  sections: ReportSection[],
  meta: ReportMeta
): string {
  const clientRows = meta.clientSummaries
    .map(
      (c) =>
        `<tr><td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;font-family:'Courier New',monospace;color:#0ea5e9;font-size:13px">${c.clientId}</td><td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;font-weight:600">${c.name || "—"}</td><td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;color:#64748b;font-size:13px">${c.meta}</td></tr>`
    )
    .join("");

  const sectionHTML = sections
    .map(
      (s, i) => `
      <div style="margin-top:32px;page-break-inside:avoid">
        <h2 style="font-size:18px;font-weight:700;color:#0f172a;border-bottom:2px solid #0ea5e9;padding-bottom:8px;margin-bottom:16px">
          ${i + 1}. ${s.title}
        </h2>
        <div style="font-size:14px;line-height:1.7;color:#334155;white-space:pre-wrap">${escapeHtml(s.content)}</div>
      </div>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @media print {
    body { margin: 0; }
    .no-print { display: none !important; }
    .page-break { page-break-before: always; }
  }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    color: #0f172a;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 32px;
    line-height: 1.6;
  }
  table { border-collapse: collapse; width: 100%; }
  th { text-align: left; padding: 8px 12px; background: #f1f5f9; border-bottom: 2px solid #cbd5e1; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; }
</style>
</head>
<body>
  <div style="text-align:center;margin-bottom:40px">
    <h1 style="font-size:24px;font-weight:800;color:#0f172a;margin:0">${escapeHtml(meta.firmName)}</h1>
    <p style="color:#64748b;font-size:14px;margin:8px 0 0">Book Review Report — ${escapeHtml(meta.date)}</p>
  </div>

  <div style="margin-bottom:32px">
    <h2 style="font-size:16px;font-weight:700;color:#0f172a;border-bottom:2px solid #0ea5e9;padding-bottom:8px;margin-bottom:12px">Clients Reviewed</h2>
    <table>
      <thead><tr><th>Client ID</th><th>Name</th><th>Details</th></tr></thead>
      <tbody>${clientRows}</tbody>
    </table>
  </div>

  ${sectionHTML}

  <div style="margin-top:48px;padding-top:24px;border-top:1px solid #e2e8f0">
    <h3 style="font-size:13px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:0.05em">Disclaimer</h3>
    <p style="font-size:12px;color:#94a3b8;line-height:1.6">${escapeHtml(meta.disclaimer)}</p>
  </div>

  <div style="margin-top:16px;text-align:center;color:#cbd5e1;font-size:11px">
    Generated by Conda Book Review Intelligence — Client names added locally, never transmitted to AI
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function downloadPDF(
  sections: ReportSection[],
  meta: ReportMeta
): Promise<void> {
  const html = buildReportHTML(sections, meta);

  const container = document.createElement("div");
  container.style.position = "fixed";
  container.style.top = "-10000px";
  container.style.left = "0";
  container.style.width = "800px";
  container.style.background = "white";
  container.innerHTML = html;
  document.body.appendChild(container);

  try {
    const html2canvas = (await import("html2canvas")).default;
    const { jsPDF } = await import("jspdf");

    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      windowWidth: 800,
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pdfWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 10;

    pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight - 20;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight + 10;
      pdf.addPage();
      pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight - 20;
    }

    pdf.save(`book-review-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}

export function printReport(
  sections: ReportSection[],
  meta: ReportMeta
): void {
  const html = buildReportHTML(sections, meta);
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 500);
}

export async function copyToClipboard(
  sections: ReportSection[],
  meta: ReportMeta
): Promise<void> {
  const html = buildReportHTML(sections, meta);
  const plainText = sections
    .map((s, i) => `${i + 1}. ${s.title}\n\n${s.content}`)
    .join("\n\n---\n\n");

  try {
    await navigator.clipboard.write([
      new ClipboardItem({
        "text/html": new Blob([html], { type: "text/html" }),
        "text/plain": new Blob([plainText], { type: "text/plain" }),
      }),
    ]);
  } catch {
    await navigator.clipboard.writeText(plainText);
  }
}

export interface ComplianceLogParams {
  firmName: string;
  advisorName?: string;
  clientCount: number;
  clientIds: string[];
  bookHeaders: string[];
  directoryHeaders: string[];
  sections: ReportSection[];
}

export function downloadComplianceLog(params: ComplianceLogParams): void {
  const sessionId = crypto.randomUUID();
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const withheldFields = params.directoryHeaders
    .filter((h) => h !== "client_id" && h !== "clientid")
    .join(", ");

  const log = `COMPLIANCE LOG — AI-ASSISTED BOOK REVIEW
${"=".repeat(50)}

Session ID:      ${sessionId}
Date:            ${dateStr} ${timeStr}
Model:           Claude Sonnet 4 (Anthropic)
Firm:            ${params.firmName}${params.advisorName ? `\nAdvisor:         ${params.advisorName}` : ""}

DATA HANDLING
${"─".repeat(50)}
• Client data transmitted using anonymized Client IDs only
• PII (names, contact info) stored locally in browser, never sent to API
• Client name re-identification performed client-side after AI analysis
• Anthropic API data retention: inputs not used for training

DATA SCOPE
${"─".repeat(50)}
• Clients analyzed: ${params.clientCount}
• Client IDs referenced in report: ${params.clientIds.join(", ")}
• Fields transmitted to AI: ${params.bookHeaders.join(", ")}
• Fields withheld from AI: ${withheldFields || "No client directory uploaded"}

REPORT SECTIONS GENERATED
${"─".repeat(50)}
${params.sections
  .map(
    (s, i) =>
      `${i + 1}. ${s.title}\n   Clients referenced: ${s.clientIdsReferenced.join(", ") || "none"}`
  )
  .join("\n")}

${"─".repeat(50)}
This compliance log was generated client-side. No data from this log was transmitted to any external service.
`;

  const blob = new Blob([log], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `compliance-log-${now.toISOString().slice(0, 10)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
